In [18]:
import numpy as np
from scipy.special import softmax

In [2]:
w1 = np.array([1, 0, 0])
w2 = np.array([0, 1, 0])
w3 = np.array([1, 1, 0])
w4 = np.array([0, 0, 1])

In [6]:
np.random.seed(42)
W_Q = np.random.randint(3, size=(3, 3))
W_K = np.random.randint(3, size=(3, 3))
W_V = np.random.randint(3, size=(3, 3))

In [15]:
query_1 = np.dot(w1, W_Q)
key_1 = np.dot(w1, W_K)
value_1 = np.dot(w1, W_V)
 
query_2 = np.dot(w2, W_Q)
key_2 = np.dot(w2, W_K)
value_2 = np.dot(w2, W_V)
 
query_3 = np.dot(w3, W_Q)
key_3 = np.dot(w3, W_K)
value_3 = np.dot(w3, W_V)
 
query_4 = np.dot(w4, W_Q)
key_4 = np.dot(w4, W_K)
value_4 = np.dot(w4, W_V)

Generam scorurile de atentie pentru primul cuvant

In [16]:
scores = np.array([
    np.dot(query_1, key_1),
    np.dot(query_1, key_2),
    np.dot(query_1, key_3),
    np.dot(query_1, key_4)
])

In [20]:
# Este o practica comuna sa impartim scorurile la radical din dimensiunea vectorilor de chei
weights = softmax(scores / key_1.shape[0] ** 0.5)

In [22]:
attention = (weights[0] * value_1) + (weights[1] * value_2) + (weights[2] * value_3) + (weights[3] * value_4)
 
print(attention)

[0.98522025 1.74174051 0.75652026]


Generam pentru toate cuvintele scorurile de atentie folosind o implementare vectorizata

In [23]:
words = np.array([
    w1,
    w2,
    w3,
    w4
])

In [24]:
Q = np.dot(words, W_Q)
K = np.dot(words, W_K)
V = np.dot(words, W_V)

In [26]:
scores = np.dot(Q, K.T)

In [27]:
scores

array([[ 8,  2, 10,  2],
       [ 4,  0,  4,  0],
       [12,  2, 14,  2],
       [10,  4, 14,  3]])

In [28]:
scores.shape

(4, 4)

In [29]:
weights = softmax(scores / K.shape[1] ** 0.5, axis=1)

In [30]:
attention = np.dot(weights, V)
 
print(attention)

[[0.98522025 1.74174051 0.75652026]
 [0.90965265 1.40965265 0.5       ]
 [0.99851226 1.75849334 0.75998108]
 [0.99560386 1.90407309 0.90846923]]


# HW
Adapteaza codul de mai sus pentru a implementa modulul de atentie Bahdanau.